export const actionTypes = {
    GET_USER: "GET_USER",
    LOADING: "LOADING",
    SIGN_OUT: "SIGN_OUT",
    GET_CODE: "GET_CODE",
    GET_LIST_USERS: "GET_LIST_USERS",
    GET_PAGE_USER: "GET_PAGE_USER",
    GET_PAGE_COURSE: "GET_PAGE_COURSE"
}