export const actionTypes = {
    GET_USER: "GET_USER",
    LOADING: "LOADING",
    SIGN_OUT: "SIGN_OUT",
    GET_CODE: "GET_CODE",
    GET_LIST_USERS: "GET_LIST_USERS",
    GET_PAGE_USER: "GET_PAGE_USER",
    GET_PAGE_COURSE: "GET_PAGE_COURSE",
    SET_LIST_SEARCH: "SET_LIST_SEARCH",
    SET_SEARCH_OPEN: "SET_SEARCH_OPEN",
    GET_LIST_COURSES: "GET_LIST_COURSES",
    CREATE_COURSE: "CREATE_COURSE",
    SET_PASS: "SET_PASS",
    SET_OBJECT_FORGOT: "SET_OBJECT_FORGOT",
    GET_LIST_LESSONS: "GET_LIST_LESSONS",
    GET_CATEGORY: "GET_CATEGORY",
    GET_COMMENT: "GET_COMMENT",
    GET_COURSES_PAGE: "GET_COURSES_PAGE"

}